module AppConstants
  ADMIN             = 'AdminProfile'
  MEMBER            = 'MemberProfile'
  DEVICE_IOS        = 'ios'
  DEVICE_ANDR       = 'android'
  DEVICE_WEB        = 'web'
  MEMBER_FOLLOWINGS = 'member_followings'
  MEMBER_FOLLOWERS  = 'member_followers'
  ACCEPTED          = 'accepted'
  PENDING           = 'pending'
  REJECTED          = 'rejected'
  TIMELINE          =  'TimeLine'
  POST              = 'Post'
  LIKED             = 'liked'
  DISLIKED          = 'disliked'
  EVENT             = 'Event'
  POST_COUNT        = 10
  NEW_EVENT         = 'New event started.'
  NEW_POST          = 'New post creted'
  POST_LIKE         = 'like on your post'
  POST_LIKE_OTHER   = 'like a post you\'re tagged in.'
  POST_COMMENT_YOUR_POST  = 'comment on your post'
  POST_COMMENT_OWN        = 'commented on his own post'
end
