module AppConstants
  ADMIN             = 'AdminProfile'
  MEMBER            = 'MemberProfile'
  DEVICE_IOS        = 'ios'
  DEVICE_ANDR       = 'android'
  DEVICE_WEB        = 'web'
  MEMBER_FOLLOWINGS = 'member_followings'
  MEMBER_FOLLOWERS  = 'member_followers'
  ACCEPTED          = 'accepted'
  PENDING           = 'pending'
  REJECTED          = 'rejected'
  TIMELINE          =  'TimeLine'
  POST              = 'Post'
  LIKED             = 'liked'
  DISLIKED          = 'disliked'
end
